#!/usr/bin/env node
/**
 * Extract the runtime design tokens of the Twilight component library from the compiled
 * Storybook stylesheet (storybook/static/styles.css) — the CSS custom properties the
 * `s-*` web components actually consume in production.
 *
 * Output: tokens/twilight-runtime.json    { light, dark, radius, shadow, fontSize, lineHeight }
 *         tokens/twilight-runtime.css     :root / .dark blocks copied verbatim
 *         docs/twilight-runtime-tokens.md tables (HSL triplets resolved to hex)
 *
 * Run: node scripts/extract_storybook_tokens.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const css = fs.readFileSync(path.join(ROOT, "storybook", "static", "styles.css"), "utf8");

function blocks(selectorRe) {
  const out = [];
  const re = /([^{}]+)\{([^{}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const sel = m[1].trim();
    if (selectorRe.test(sel) && /--[a-z]/.test(m[2])) out.push({ sel, body: m[2] });
  }
  return out;
}
function decls(body) {
  const o = {};
  for (const d of body.split(";")) {
    const i = d.indexOf(":");
    if (i < 0) continue;
    const k = d.slice(0, i).trim();
    const v = d.slice(i + 1).trim().replace(/\s+/g, " ");
    if (k.startsWith("--") && !k.startsWith("--tw-") && !k.startsWith("--toastify")) o[k] = v;
  }
  return o;
}
function hslToHex(str) {
  const m = str.match(/^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%\s+(\d+(?:\.\d+)?)%$/);
  if (!m) return null;
  const h = Number(m[1]), s = Number(m[2]) / 100, l = Number(m[3]) / 100;
  const c = (1 - Math.abs(2 * l - 1)) * s, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), mm = l - c / 2;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return "#" + [r, g, b].map((v) => Math.round((v + mm) * 255).toString(16).padStart(2, "0")).join("");
}

const light = {}, dark = {};
for (const b of blocks(/^:root$/)) Object.assign(light, decls(b.body));
for (const b of blocks(/^\.dark$/)) Object.assign(dark, decls(b.body));
const annotate = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, { raw: v, hex: hslToHex(v) }]));

// utility scales Tailwind compiled from the theme (radius, shadows, font sizes)
const scale = (prefix, prop) => {
  const o = {};
  const re = new RegExp(`\\.(${prefix}(?:-[a-z0-9]+)?)\\{([^}]*)\\}`, "g");
  let m;
  while ((m = re.exec(css))) {
    const d = m[2].match(new RegExp(`(?:^|;)${prop}:([^;]+)`));
    if (d && o[m[1]] === undefined) o[m[1]] = d[1].trim();
  }
  return o;
};
const radius = scale("rounded", "border-radius");
const shadow = scale("shadow", "--tw-shadow");
const fontSize = scale("text", "font-size");
const lineHeight = scale("text", "line-height");

const out = { source: "storybook/static/styles.css", light: annotate(light), dark: annotate(dark), radius, shadow, fontSize, lineHeight };
fs.writeFileSync(path.join(ROOT, "tokens", "twilight-runtime.json"), JSON.stringify(out, null, 2) + "\n");

const rootBlock = blocks(/^:root$/).map((b) => `:root {${b.body}}`).join("\n");
const darkBlock = blocks(/^\.dark$/).map((b) => `.dark {${b.body}}`).join("\n");
fs.writeFileSync(path.join(ROOT, "tokens", "twilight-runtime.css"),
  `/* Runtime CSS custom properties of the Twilight (s-*) component library, copied from the compiled Storybook stylesheet.\n   Colors are HSL triplets meant for hsl(var(--name) / <alpha>). Generated by scripts/extract_storybook_tokens.mjs. */\n${rootBlock}\n${darkBlock}\n`);

const sw = (hex) => (hex ? `<img src="https://placehold.co/14x14/${hex.slice(1)}/${hex.slice(1)}.png" alt="" /> \`${hex}\`` : "");
const md = ["# Twilight runtime tokens", "",
  "CSS custom properties consumed by the production `s-*` web components (Stencil + Tailwind), extracted from the",
  "compiled Storybook stylesheet. Color values are **HSL triplets** used as `hsl(var(--primary) / 1)`; the hex column",
  "is the resolved color. `.dark` lists the dark-theme overrides. Generated by `scripts/extract_storybook_tokens.mjs`.",
  "For the Figma-side tokens see [foundations.md](foundations.md).", "",
  "## Light theme (`:root`)", "", "| Variable | Value | Hex |", "|---|---|---|"];
for (const [k, v] of Object.entries(out.light)) md.push(`| \`${k}\` | \`${v.raw}\` | ${sw(v.hex)} |`);
md.push("", "## Dark theme overrides (`.dark`)", "", "| Variable | Value | Hex |", "|---|---|---|");
for (const [k, v] of Object.entries(out.dark)) md.push(`| \`${k}\` | \`${v.raw}\` | ${sw(v.hex)} |`);
const tbl = (title, o) => { md.push("", `## ${title}`, "", "| Class | Value |", "|---|---|"); for (const [k, v] of Object.entries(o)) md.push(`| \`.${k}\` | \`${v}\` |`); };
tbl("Radius scale", radius); tbl("Shadow scale", shadow); tbl("Font sizes", fontSize);
fs.writeFileSync(path.join(ROOT, "docs", "twilight-runtime-tokens.md"), md.join("\n") + "\n");
console.log(`light=${Object.keys(light).length} dark=${Object.keys(dark).length} radius=${Object.keys(radius).length} shadow=${Object.keys(shadow).length} fontSize=${Object.keys(fontSize).length}`);
