#!/usr/bin/env python3
"""Compare Figma design tokens (tokens/tokens.flat.json) with the runtime CSS variables of the
Twilight components (tokens/twilight-runtime.json) and write docs/token-parity.md.

Run: python3 scripts/token_parity.py
"""
import json, os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
figma = json.load(open(os.path.join(ROOT, "tokens", "tokens.flat.json")))
rt = json.load(open(os.path.join(ROOT, "tokens", "twilight-runtime.json")))

fig_by_hex = defaultdict(list)
for name, v in figma.items():
    if isinstance(v, str) and v.startswith("#") and len(v) == 7:
        fig_by_hex[v.lower()].append(name)

def close(a, b, tol=6):
    ra, ga, ba = int(a[1:3], 16), int(a[3:5], 16), int(a[5:7], 16)
    rb, gb, bb = int(b[1:3], 16), int(b[3:5], 16), int(b[5:7], 16)
    return max(abs(ra - rb), abs(ga - gb), abs(ba - bb)) <= tol

lines = ["# Token parity: Figma variables vs. runtime CSS variables", "",
         "For every color custom property the production `s-*` components use (light theme, `tokens/twilight-runtime.json`),",
         "the Figma variables (`tokens/tokens.flat.json`) with the same or a near-identical (±6/255 per channel, HSL rounding) value.",
         "Generated by `scripts/token_parity.py`.", "",
         "| Runtime variable | Hex | Matching Figma variables |", "|---|---|---|"]
exact = near = none = 0
for name, v in rt["light"].items():
    hx = v.get("hex")
    if not hx:
        continue
    m = fig_by_hex.get(hx)
    if m:
        exact += 1; tag = ""
    else:
        m = [n for h, ns in fig_by_hex.items() if close(h, hx) for n in ns]
        if m: near += 1; tag = " *(≈)*"
        else: none += 1; tag = ""
    lines.append(f"| `{name}` | <img src=\"https://placehold.co/14x14/{hx[1:]}/{hx[1:]}.png\" alt=\"\" /> `{hx}` | " + (", ".join(f"`{n}`" for n in sorted(m)[:6]) + (f" … (+{len(m)-6})" if len(m) > 6 else "") + tag if m else "—") + " |")
lines += ["", f"Exact matches: {exact} · near matches: {near} · no Figma equivalent: {none}.", "",
          "## Reading the table", "",
          "- Runtime colors are HSL triplets (`--primary: 189 100% 17%` → `hsl(var(--primary) / <alpha>)`), so a ±1 rounding difference from the Figma hex is expected.",
          "- Runtime names are *palette* names (`--primary-500`, `--gray-200`); Figma names are *semantic* (`background/primary/primary`, `border/default`). Use this table to translate between the two when implementing a Figma spec with the `s-*` components or Tailwind classes (`bg-primary`, `text-gray-500`).",
          "- Variables without a Figma equivalent (e.g. `--mahally-*`, `--moshammer-*`, chart colors, layout sizes) are product-specific runtime values that are not modelled in the Figma library."]
open(os.path.join(ROOT, "docs", "token-parity.md"), "w").write("\n".join(lines) + "\n")
print(f"exact={exact} near={near} none={none}")
